export const DefaultUIAction = {
  CALL: 'call',

  NOTIFY_VIEW_READY: 'NOTIFY:VIEW_READY',

  REQUEST_RESET: 'REQUEST:RESET',
  REQUEST_STATE: 'REQUEST:STATE',

  RESPONSE_STATE: 'RESPONSE:STATE',
};