version: "2"         # required to adjust maintainability checks
checks:
  file-lines:
    config:
      threshold: 750
  method-complexity:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/*.d.ts"
  - "**/*.test.*"
  - "**/.vscode/"