-- @conn PGSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS company;

-- @block create company table
-- @conn PGSQL
CREATE TABLE IF NOT EXISTS COMPANY(
  ID UUID PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  AGE INT NOT NULL,
  ADDRESS CHAR(50),
  SALARY REAL
);


-- @block create department table
CREATE TABLE IF NOT EXISTS DEPARTMENT(
  ID INT PRIMARY KEY NOT NULL,
  DEPT CHAR(50) NOT NULL,
  EMP_ID UUID NOT NULL,
  COMPANY_ID UUID NOT NULL,
  CONSTRAINT fk_company FOREIGN KEY(COMPANY_ID) REFERENCES company(ID)
);

SELECT VERSION()