/// <reference types="react" />
import Area from './components/area';
import Bar from './components/bar';
import Bullet from './components/bullet';
import Column from './components/column';
import Funnel from './components/funnel';
import Histogram from './components/histogram';
import Line from './components/line';
import Box from './components/box';
import Liquid from './components/liquid';
import Heatmap from './components/heatmap';
import Pie from './components/pie';
import Gauge from './components/gauge';
import Progress from './components/progress';
import Radar from './components/radar';
import RingProgress from './components/ring-progress';
import Rose from './components/rose';
import Chord from './components/chord';
import Scatter from './components/scatter';
import TinyArea from './components/tiny-area';
import TinyColumn from './components/tiny-column';
import DualAxes from './components/dual-axes';
import TinyLine from './components/tiny-line';
import Waterfall from './components/waterfall';
import WordCloud from './components/word-cloud';
import Sunburst from './components/sunburst';
import Stock from './components/stock';
import RadialBar from './components/radial-bar';
import Sankey from './components/sankey';
import Treemap from './components/treemap';
import Violin from './components/violin';
import Venn from './components/venn';
import CirclePacking from './components/circle-packing';
import Facet from './components/facet';
import MultiView from './components/mix';
import Mix from './components/mix';
import BidirectionalBar from './components/bidirectional-bar';
import { G2, flow, measureTextWidth, adaptors, getCanvasPattern, FUNNEL_CONVERSATION_FIELD } from '@antv/g2plot';
export { Area, Bar, Box, Bullet, Column, Funnel, Histogram, Line, Liquid, Heatmap, Pie, Progress, Radar, Facet, RingProgress, Rose, Chord, Scatter, TinyArea, TinyColumn, TinyLine, Waterfall, WordCloud, Sunburst, DualAxes, Stock, RadialBar, CirclePacking, Gauge, Sankey, Treemap, Violin, Venn, MultiView, Mix, BidirectionalBar, G2, getCanvasPattern, FUNNEL_CONVERSATION_FIELD, flow, measureTextWidth, adaptors, };
declare const _default: {
    Area: import("react").ForwardRefExoticComponent<import("./interface").AreaConfig & import("react").RefAttributes<unknown>>;
    Bar: import("react").ForwardRefExoticComponent<import("./interface").BarConfig & import("react").RefAttributes<unknown>>;
    Box: import("react").ForwardRefExoticComponent<import("./interface").BoxConfig & import("react").RefAttributes<unknown>>;
    Bullet: import("react").ForwardRefExoticComponent<import("./interface").BulletConfig & import("react").RefAttributes<unknown>>;
    Column: import("react").ForwardRefExoticComponent<import("./interface").ColumnConfig & import("react").RefAttributes<unknown>>;
    Funnel: import("react").ForwardRefExoticComponent<import("./interface").FunnelConfig & import("react").RefAttributes<unknown>>;
    Histogram: import("react").ForwardRefExoticComponent<import("./interface").HistogramConfig & import("react").RefAttributes<unknown>>;
    Line: import("react").ForwardRefExoticComponent<import("./interface").LineConfig & import("react").RefAttributes<unknown>>;
    Liquid: import("react").ForwardRefExoticComponent<import("./interface").LiquidConfig & import("react").RefAttributes<unknown>>;
    Heatmap: import("react").ForwardRefExoticComponent<import("./interface").HeatmapConfig & import("react").RefAttributes<unknown>>;
    Pie: import("react").ForwardRefExoticComponent<import("./interface").PieConfig & import("react").RefAttributes<unknown>>;
    Progress: import("react").ForwardRefExoticComponent<import("./interface").ProgressConfig & import("react").RefAttributes<unknown>>;
    Radar: import("react").ForwardRefExoticComponent<import("./interface").RadarConfig & import("react").RefAttributes<unknown>>;
    Facet: import("react").ForwardRefExoticComponent<import("./interface").FacetConfig & import("react").RefAttributes<unknown>>;
    RingProgress: import("react").ForwardRefExoticComponent<import("./interface").RingProgressConfig & import("react").RefAttributes<unknown>>;
    Rose: import("react").ForwardRefExoticComponent<import("./interface").RoseConfig & import("react").RefAttributes<unknown>>;
    Chord: import("react").ForwardRefExoticComponent<import("./components/chord").ChordConfig & import("react").RefAttributes<unknown>>;
    Scatter: import("react").ForwardRefExoticComponent<import("./interface").ScatterConfig & import("react").RefAttributes<unknown>>;
    TinyArea: import("react").ForwardRefExoticComponent<import("./interface").TinyAreaConfig & import("react").RefAttributes<unknown>>;
    TinyColumn: import("react").ForwardRefExoticComponent<import("./interface").TinyColumnConfig & import("react").RefAttributes<unknown>>;
    TinyLine: import("react").ForwardRefExoticComponent<import("./interface").TinyLineConfig & import("react").RefAttributes<unknown>>;
    Waterfall: import("react").ForwardRefExoticComponent<import("./interface").WaterfallConfig & import("react").RefAttributes<unknown>>;
    WordCloud: import("react").ForwardRefExoticComponent<import("./interface").WordCloudConfig & import("react").RefAttributes<unknown>>;
    Sunburst: import("react").ForwardRefExoticComponent<import("./interface").SunburstConfig & import("react").RefAttributes<unknown>>;
    DualAxes: import("react").ForwardRefExoticComponent<import("./interface").DualAxesConfig & import("react").RefAttributes<unknown>>;
    Stock: import("react").ForwardRefExoticComponent<import("./interface").StockConfig & import("react").RefAttributes<unknown>>;
    RadialBar: import("react").ForwardRefExoticComponent<import("./interface").RadialBarConfig & import("react").RefAttributes<unknown>>;
    Gauge: import("react").ForwardRefExoticComponent<import("./interface").GaugeConfig & import("react").RefAttributes<unknown>>;
    CirclePacking: import("react").ForwardRefExoticComponent<import("./interface").CirclePackingConfig & import("react").RefAttributes<unknown>>;
    Sankey: import("react").ForwardRefExoticComponent<import("./interface").SankeyConfig & import("react").RefAttributes<unknown>>;
    Treemap: import("react").ForwardRefExoticComponent<import("./components/treemap").TreemapConfig & import("react").RefAttributes<unknown>>;
    Violin: import("react").ForwardRefExoticComponent<import("./interface").ViolinConfig & import("react").RefAttributes<unknown>>;
    Venn: import("react").ForwardRefExoticComponent<import("./interface").VennConfig & import("react").RefAttributes<unknown>>;
    MultiView: import("react").ForwardRefExoticComponent<import("./interface").MixConfig & import("react").RefAttributes<unknown>>;
    Mix: import("react").ForwardRefExoticComponent<import("./interface").MixConfig & import("react").RefAttributes<unknown>>;
    BidirectionalBar: import("react").ForwardRefExoticComponent<import("./interface").BidirectionalBarConfig & import("react").RefAttributes<unknown>>;
    getCanvasPattern: typeof getCanvasPattern;
    FUNNEL_CONVERSATION_FIELD: string;
    G2: typeof G2;
    flow: typeof flow;
    measureTextWidth: {
        (...args: any[]): any;
        cache: Map<any, any>;
    };
    adaptors: {
        scale: typeof import("@antv/g2plot/lib/adaptor/common").scale;
        legend: typeof import("@antv/g2plot/lib/adaptor/common").legend;
        tooltip: typeof import("@antv/g2plot/lib/adaptor/common").tooltip;
        annotation: typeof import("@antv/g2plot/lib/adaptor/common").annotation;
        interaction: typeof import("@antv/g2plot/lib/adaptor/common").interaction;
        theme: typeof import("@antv/g2plot/lib/adaptor/common").theme;
        animation: typeof import("@antv/g2plot/lib/adaptor/common").animation;
    };
};
export default _default;
export * from './interface';
