-- Extracted from w3schools

CREATE TABLE ACCOUNTABILITY (
	ID INT PRIMARY KEY,
    REF_NAME VARCHAR (50)
);

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
	EMPLOYEE_NAME VARCHAR (50),
    ACCOUNTABILITY_ID INT NOT NULL,
    FOREIGN KEY (ACCOUNTABILITY_ID) REFERENCES ACCOUNTABILITY(ID)
);

