export declare const SHAPE_TO_TAGS: {
    rect: string;
    circle: string;
    line: string;
    path: string;
    marker: string;
    text: string;
    polyline: string;
    polygon: string;
    image: string;
    ellipse: string;
    dom: string;
};
export declare const SVG_ATTR_MAP: {
    opacity: string;
    fillStyle: string;
    fill: string;
    fillOpacity: string;
    strokeStyle: string;
    strokeOpacity: string;
    stroke: string;
    x: string;
    y: string;
    r: string;
    rx: string;
    ry: string;
    width: string;
    height: string;
    x1: string;
    x2: string;
    y1: string;
    y2: string;
    lineCap: string;
    lineJoin: string;
    lineWidth: string;
    lineDash: string;
    lineDashOffset: string;
    miterLimit: string;
    font: string;
    fontSize: string;
    fontStyle: string;
    fontVariant: string;
    fontWeight: string;
    fontFamily: string;
    startArrow: string;
    endArrow: string;
    path: string;
    class: string;
    id: string;
    style: string;
    preserveAspectRatio: string;
};
export declare const EVENTS: string[];
