# https://code.visualstudio.com/api/working-with-extensions/continuous-integration

name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        HUSKY_SKIP_INSTALL: "true"
        CXX: "g++-4.9"
        CC: "gcc-4.9"
        DISPLAY: ":99.0"
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        yarn

    - name: test & build
      env:
        HUSKY_SKIP_INSTALL: "true"
        CXX: "g++-4.9"
        CC: "gcc-4.9"
        DISPLAY: ":99.0"
      run: |
        yarn test:older --no-coverage
        yarn test

    - uses: codecov/codecov-action@v1.0.2
      if: github.event_name == 'push'
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
