name: Formatter Test & Build

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        HUSKY_SKIP_INSTALL: "true"
      run: |
        yarn

    - name: test & build
      env:
        HUSKY_SKIP_INSTALL: "true"
      run: |
        cd packages/formatter
        yarn
        yarn pack

    - name: 'Upload tgz'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./packages/formatter/*.tgz

    # - uses: codecov/codecov-action@v1.0.2
    #   with:
    #     token: ${{secrets.CODECOV_TOKEN}} #required
