# https://code.visualstudio.com/api/working-with-extensions/continuous-integration

name: Formatter Test & Build
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - env:
        HUSKY_SKIP_INSTALL: "true"
      run: |
        yarn

    - name: test & build
      env:
        HUSKY_SKIP_INSTALL: "true"
      run: |
        cd packages/formatter
        yarn
        yarn run check
        echo ">>> Compiled vscode-test"
        echo ">>> Run sample integration test"
        yarn pack

    - name: 'Upload tgz'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./*.tgz

    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
