import { DefaultUIAction } from '@sqltools/vscode/webview-provider/action';

export const UIAction = {
  ...DefaultUIAction,

  REQUEST_INSTALLED_DRIVERS: 'REQUEST:INSTALLED_DRIVERS',

  REQUEST_OPEN_CONNECTION_FILE: 'REQUEST:OPEN_CONNECTION_FILE',
  REQUEST_EDIT_CONNECTION: 'REQUEST:EDIT_CONNECTION',
  REQUEST_SYNC_CONSOLE_MESSAGES: 'REQUEST:SYNC_CONSOLE_MESSAGES',
  REQUEST_CREATE_CONNECTION: 'REQUEST:CREATE_CONNECTION',
  REQUEST_UPDATE_CONNECTION: 'REQUEST:UPDATE_CONNECTION',
  REQUEST_TEST_CONNECTION: 'REQUEST:TEST_CONNECTION',

  RESPONSE_INSTALLED_DRIVERS: 'RESPONSE:INSTALLED_DRIVERS',
  RESPONSE_QUERY_RESULTS: 'RESPONSE:QUERY_RESULTS',
  RESPONSE_UPDATE_CONNECTION_SUCCESS: 'RESPONSE:UPDATE_CONNECTION_SUCCESS',
  RESPONSE_UPDATE_CONNECTION_ERROR: 'RESPONSE:UPDATE_CONNECTION_ERROR',
  RESPONSE_CREATE_CONNECTION_SUCCESS: 'RESPONSE:CREATE_CONNECTION_SUCCESS',
  RESPONSE_CREATE_CONNECTION_ERROR: 'RESPONSE:CREATE_CONNECTION_ERROR',
  RESPONSE_TEST_CONNECTION_WARNING: 'RESPONSE:TEST_CONNECTION_WARNING',
  RESPONSE_TEST_CONNECTION_SUCCESS: 'RESPONSE:TEST_CONNECTION_SUCCESS',
  RESPONSE_TEST_CONNECTION_ERROR: 'RESPONSE:TEST_CONNECTION_ERROR',
};